# Pytorch基本知识-Tensor

In [3]:
# first of all, import pytorch
import torch

print(torch.__version__, torch.version.cuda)

1.10.0 10.2


## tensor的生成

tensor 是pytorch以及深度学习中默认的数据格式，是最基本的组成单元。虽然可以使用torch.Tensor()构建一个张量，但是不推荐，因为这个默认是32bit-float类型的数据；相反的，**推荐使用工厂函数，like torch.empty()、torch.zeros()、torch.ones()，并用dtype指定数据类型**。
```python
tensor = torch.empty((2, 3), dtype=torch.float64)  # 构造一个 torch.DoubleTensor (float64)

tensor = torch.zeros((3, 3), dtype=torch.int32)  # 构造一个 torch.IntTensor (int32)

tensor = torch.ones((4, 4), dtype=torch.bool)  # 构造一个 torch.BoolTensor

```

同时，torch.tensor()总是会复制你的数据，如果不需要为其计算梯度，可以使用下面的方法：
```python
data = torch.tensor([1.0, 2.0, 3.0], requires_grad=False)
data.requires_grad_()  # 现在 requires_grad=True, 并且没有创建副本

data = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
no_grad_data = data.detach()  # 生成不需要梯度的新张量，数据存储是共享的

```

如果有一个Numpy数组，并想转为tensor类型，推荐如下操作，因为这直接使用numpy的内存地址，而不需要新建。
```python
import numpy as np
np_array = np.array([1.0, 2.0, 3.0])
tensor = torch.as_tensor(np_array)  # 不进行内存拷贝，直接使用相同的内存

```

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

## tensor的形状

tensor.ndim 指的是张量（Tensor）的维度数量，也称为“张量的阶数”或“张量的秩”。它表示张量的结构有多少个维度（轴），可以理解为该张量是几维数组。标量是 0 维的，向量是 1 维的，矩阵是 2 维的。

In [5]:
scalar.ndim

0

In [6]:
scalar.item() # 将标量tensor变为一个数值。

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
print('the dimension of a vector is :',vector.ndim )
print('the shape of a vector is :', vector.shape)

the dimension of a vector is : 1
the shape of a vector is : torch.Size([2])


In [10]:
matrix = torch.tensor([[7,8],[5,6]])
matrix

tensor([[7, 8],
        [5, 6]])

In [13]:
print('the dimensions of a matrix is :',matrix.ndim)
print('the shape of a matrix is :',matrix.shape)

the dimensions of a matrix is : 2
the shape of a matrix is : torch.Size([2, 2])


In [14]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
print('the dimensions of a tensor is',tensor.ndim)
print('the shape of a tensor is',tensor.shape) # 由外向内看中括号，中括号间的逗号数就代表数量

the dimensions of a tensor is 3
the shape of a tensor is torch.Size([1, 3, 3])


## tensor工厂函数生成

深度学习参数更新过程
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

下面使用随机方法构建tensor

In [20]:
random_tensor = torch.rand(size = (3,4)) # 用tuple数据类型指定生成的格式
random_tensor,random_tensor.dtype

(tensor([[0.8867, 0.6970, 0.6490, 0.2785],
         [0.0348, 0.0394, 0.8291, 0.6344],
         [0.0157, 0.0036, 0.4928, 0.8933]]),
 torch.float32)

In [21]:
zeros = torch.zeros(size = (3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
ones = torch.ones(size = (3, 4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [23]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten


C:\Users\86182\AppData\Local\Temp\ipykernel_28860\232764869.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## tensor的三件套

在实际操作中，引起报错的主要原因往往是tensor的数据格式不一致、数据类型不一致、数据不在同一个设备上。

In [26]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_16_tensor.shape,float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

## 操作tensor

深度学习中，数据基本都是以tensor来展现的。模型学习数据中的特征也是通过大量的运算得到的，就是基本的四则运算以及矩阵操作等。四则运算并不会改变tensor内部的值，除非被重新分配 tensor = ...。

In [30]:
tensor = torch.tensor([1,2,3])
tensor + 10,tensor * 10, tensor

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([1, 2, 3]))

In [31]:
# Can also use torch functions
torch.multiply(tensor, 10)


tensor([10, 20, 30])

## 矩阵乘法

最重要的运算操作就是矩阵乘法-> @，只需要满足inner dimensions match and the resulting matrix has the shape of the outer dimensions. thats all.
注意矩阵的乘法和元素的乘法（*）是不一样的。

In [33]:
tensor1 = torch.rand(size = (3,4))
tensor2 = torch.rand(size = (4,3))
tensor = tensor1 @ tensor2
tensor,tensor.shape

(tensor([[1.1608, 0.8483, 0.9520],
         [1.1274, 0.9002, 1.2802],
         [1.4138, 1.0658, 1.5958]]),
 torch.Size([3, 3]))

In [38]:
# 设置torch的随即种子
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 2,
                         out_features=6)
x = torch.rand(size=(3,2))
out = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{out}\n\nOutput shape: {out.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## 基本的统计运算

包括数的统计运算以及索引值的查找

In [39]:
x = torch.arange(0,100,10)
print(f'the sum of x is {sum(x)}')
print(f'the max num of x is {x.max()}, while the min num of x is {x.min()}')
print(f'Mean{x.type(torch.float32).mean()}')

the sum of x is 450
the max num of x is 90, while the min num of x is 0
Mean45.0


> **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail. 

In [41]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [42]:
# 修改数据类型，防止出现不匹配的现象
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## 改变tensor的形状

只改变tensor的形状，而不改变tensor的值
| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

In [43]:
x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [44]:
# 添加一个维度
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [47]:
# 使用view也是可以的，同样是数据不变，格式改变
# 但是要注意，view相当于为原有的tensor创建了一个
# 新的数据视图，改变新的view也会导致tensor改变
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [50]:
# 将多个tensor按照给定的维度堆积
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [51]:
# 移除维度数为1的维度，只有>=2的才会被保留
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [52]:
# squeeze的反向操作，在指定的维度上添加值为1的新维度
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [53]:
# 改变轴的顺序
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
# shifts axis 0->1, 1->2, 2->0 对轴的顺序重新排列
x_permuted = x_original.permute(2, 0, 1) 

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## tensor的索引

根据索引取tensor指定位置的数

In [54]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [55]:
# 也可以用：表示该维度所有元素，进行取数
print(f"First square bracket:\n{x[:]}") 
print(f"Second square bracket: {x[:,0]}") 
print(f"Third square bracket: {x[:,:,0]}")

First square bracket:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Second square bracket: tensor([[1, 2, 3]])
Third square bracket: tensor([[1, 4, 7]])


## pytorch与numpy

常用的就是tensor与ndarray的互相转化


In [57]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

## GPU运算


In [58]:
torch.cuda.is_available()

True

In [59]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Count number of devices
torch.cuda.device_count()

1

In [60]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [61]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)